services:
  _base:
    image: base-data:1.0
    volumes:
      - ${INSTALL}/hbase:/opt/bigdata/hbase
      - ./etc/hbase:/opt/bigdata/etc/hbase
      - ./script:/opt/bigdata/script
  hmaster:
    extends:
      service: _base
    working_dir: /opt/bigdata
    hostname: hmaster
    networks:
      - cluster_net
    env_file:
      - .env
networks:
  cluster_net:
    external: true
