services:
  _base:
    image: base-data:1.0
    volumes:
      - ./hadoop:/opt/bigdata/install
      - ./etc/hadoop-cli:/opt/bigdata/etc/hadoop
      - ./script:/opt/bigdata/script
  flink01:
    extends:
      service: _base
    working_dir: /opt/bigdata
    hostname: flink
    volumes:
      - ./flink:/opt/bigdata/flink
      - ./etc/flink:/opt/bigdata/etc/flink
    networks:
      - cluster_net
    env_file:
      - .env

networks:
  cluster_net:
    external: true
