# CentOS with JDK 8
# Author        qiwei

# build a new image with basic  centos
FROM hd-container:1.0
# who is the author
MAINTAINER qiwei
RUN yum -y  krb5-server krb5-libs krb5-auth-dialog


CMD ["/usr/sbin/init"]
