#!/bin/bash
export BIGDATAHOME=/opt/bigdata

if [[ -d "$BIGDATAHOME/hadoop" ]]; then
  export HADOOP_CLASSPATH=$BIGDATAHOME/hadoop
  export HADOOP_HOME=$BIGDATAHOME/hadoop
fi

if [[ -d "$BIGDATAHOME/hive" ]]; then
  export HIVE_HOME=$BIGDATAHOME/hive
fi

if [[ -d "$BIGDATAHOME/tez" ]]; then
  export TEZ_CONF_DIR=$BIGDATA_CONF/tez
  export TEZ_JARS=$BIGDATAHOME/tez
  export HADOOP_CLASSPATH=${TEZ_CONF_DIR}:${TEZ_JARS}/*:${TEZ_JARS}/lib/*
fi

if [[ -d "$BIGDATAHOME/zookeeper" ]]; then
  export ZOO_HOME=$BIGDATAHOME/zookeeper
fi

if [[ -d "$BIGDATAHOME/hbase" ]]; then
  export HBASE_HOME=$BIGDATAHOME/hbase
fi

if [[ -d "$BIGDATAHOME/kafka" ]]; then
  export KAFKA_HOME=$BIGDATAHOME/kafka
fi

if [[ -d "$BIGDATAHOME/kafka-manager" ]]; then
  export KAFKA_MANAGER_HOME=$BIGDATAHOME/kafka-manager
fi

if [[ -d "$BIGDATAHOME/alluxio" ]]; then
  export ALLUXIO_HOME=$BIGDATAHOME/alluxio
fi

if [[ -d "$BIGDATAHOME/spark" ]]; then
  export SPARK_HOME=$BIGDATAHOME/spark
fi

if [[ -n $HADOOP_HOME ]]; then
  export PATH=$HADOOP_HOME/bin:$PATH
  export PATH=$HADOOP_HOME/sbin:$PATH
fi

if [[ -n $ALLUXIO_HOME ]]; then
  export PATH=$ALLUXIO_HOME/bin:$PATH
fi

if [[ -n $HIVE_HOME ]]; then
  export PATH=$HIVE_HOME/bin:$PATH
fi

if [[ -n $ZOO_HOME ]]; then
  export PATH=$ZOO_HOME/bin:$PATH
fi

if [[ -n $KAFKA_HOME ]]; then
  export PATH=$KAFKA_HOME/bin:$PATH
  export PATH=$KAFKA_MANAGER_HOME/bin:$PATH
fi

if [[ -n $HBASE_HOME ]]; then
  export PATH=$HBASE_HOME/bin:$PATH
  export PATH=$HBASE_HOME/sbin:$PATH
fi

if [[ -n $SPARK_HOME ]]; then
  export PATH=$SPARK_HOME/bin:$SPARK_HOME/sbin:$PATH
fi
