services:
  _base:
    image: base-data:1.0
    volumes:
      - ${INSTALL}/hadoop:/opt/bigdata/hadoop
      - ./etc/hadoop-default:/opt/bigdata/etc/hadoop
      - ./script:/opt/bigdata/script
    networks:
      - cluster_net
    env_file:
      - .env
  master01:
    extends:
      service: _base
    hostname: master01
    working_dir: /opt/bigdata
    ports:
      - "50070:50070"
      - "8088:8088"
      - "18088:18088"
    command: ["bash","./script/nn.sh"]
  slave01:
    working_dir: /opt/bigdata
    extends:
      service: _base
    tty: true
    command: ["bash","./script/dn.sh"]
networks:
  cluster_net:
    external: true
