version: '3'
services:
  master01:
    image: base-data:1.0
    build:
      context: .
      dockerfile: Dockerfile-ubuntu-jdk11
    working_dir: /opt/bigdata
    hostname: master01
    volumes:
      - ./install:/opt/bigdata/hadoop
      - ./etc/hadoop-default:/opt/bigdata/etc/hadoop
      - ./script:/opt/bigdata/script
    networks:
      - cluster_net
    ports:
      - "50070:50070"
      - "8088:8088"
    env_file:
      - .env
        #entrypoint: ["bash","/opt/bigdata/script/nn.sh"]
  slave01:
    image: base-data:1.0
    build:
      context: .
      dockerfile: Dockerfile-ubuntu-jdk11
    working_dir: /opt/bigdata
    hostname: slave01
    volumes:
      - ./install:/opt/bigdata/hadoop
      - ./etc/hadoop-default:/opt/bigdata/etc/hadoop
    networks:
      - cluster_net
    env_file:
      - .env

networks:
  cluster_net:
    external: true
