# CentOS with JDK 8
# Author        qiwei

# build a new image with basic  centos
FROM centos:7
# who is the author
MAINTAINER qiwei

RUN yum install -y krb5-server krb5-libs krb5-auth-dialog krb5-workstation

CMD ["/usr/sbin/init"]
